In [1]:
import pandas as pd # primeiro fiz os imports das duas bibs usadas nas aulas

In [2]:
import numpy as np

In [3]:
# link para o kaggle: https://www.kaggle.com/datasets/llatyki/brazilan-agricultural-production/data
agro = pd.read_csv('production.csv') # utilizei as habilidades da aula de entrada e saida

In [4]:
agro.head(459) # propriedades de verificação aqui cada coluna é uma seriers e o conjjunto das mesmas é um dataframe

,Unnamed: 0,Grain,Year,Alta Floresta D'Oeste (RO),Ariquemes (RO),Cabixi (RO),Cacoal (RO),Cerejeiras (RO),Colorado do Oeste (RO),Corumbiara (RO),...,Uruaçu (GO),Uruana (GO),Urutaí (GO),Valparaíso de Goiás (GO),Varjão (GO),Vianópolis (GO),Vicentinópolis (GO),Vila Boa (GO),Vila Propício (GO),Brasília (DF)
0,0,Sorghum,1974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Wheat,1974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Sorghum,1975,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Wheat,1975,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Sorghum,1976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
454,454,Barley,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
455,455,Pea,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0
456,456,Barley,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.5
457,457,Pea,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0
458,458,Barley,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.5

In [5]:
agro.notna().sum().head(20) # suspeitei que poderia ter algum erro por contra da grande quantidade de valores nam, para sanar isso somei os não nulos de cada coluna 
# usei as habilidades de tratamento de dados nulos

Unnamed: 0                       460
Grain                            460
Year                             460
Alta Floresta D'Oeste (RO)        72
Ariquemes (RO)                    97
Cabixi (RO)                       82
Cacoal (RO)                       91
Cerejeiras (RO)                  102
Colorado do Oeste (RO)           104
Corumbiara (RO)                   75
Costa Marques (RO)                76
Espigão D'Oeste (RO)              86
Guajará-Mirim (RO)                90
Jaru (RO)                         77
Ji-Paraná (RO)                    82
Machadinho D'Oeste (RO)           73
Nova Brasilândia D'Oeste (RO)     62
Ouro Preto do Oeste (RO)          73
Pimenta Bueno (RO)                93
Porto Velho (RO)                 106
dtype: int64

In [6]:
# como o data set ta certo 
agro.drop(["Unnamed: 0"], axis=1, inplace=True) # apliquei para tirar a coluna de idx duplicada

In [7]:
agro.head(459) # está certo foi removida

,Grain,Year,Alta Floresta D'Oeste (RO),Ariquemes (RO),Cabixi (RO),Cacoal (RO),Cerejeiras (RO),Colorado do Oeste (RO),Corumbiara (RO),Costa Marques (RO),...,Uruaçu (GO),Uruana (GO),Urutaí (GO),Valparaíso de Goiás (GO),Varjão (GO),Vianópolis (GO),Vicentinópolis (GO),Vila Boa (GO),Vila Propício (GO),Brasília (DF)
0,Sorghum,1974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Wheat,1974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sorghum,1975,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Wheat,1975,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Sorghum,1976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
454,Barley,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
455,Pea,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0
456,Barley,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.5
457,Pea,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0
458,Barley,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.5

In [8]:
agro['Grain'].unique() # verificando os tipos de graos

array(['Sorghum', 'Wheat', 'Maize', 'Soybeans', 'Fava Beans', 'Beans',
       'Oats', 'Rye', 'Barley', 'Pea'], dtype=object)

In [9]:
agro_long = agro.melt(id_vars=['Grain', 'Year'], var_name='State', value_name='Production')

pivot = agro_long.pivot_table(index=['State', 'Grain'], columns='Year', values='Production', aggfunc='sum')

In [10]:
agro_long # organizei os municipios juunto

           Grain  Year                       State  Production
0        Sorghum  1974  Alta Floresta D'Oeste (RO)         NaN
1          Wheat  1974  Alta Floresta D'Oeste (RO)         NaN
2        Sorghum  1975  Alta Floresta D'Oeste (RO)         NaN
3          Wheat  1975  Alta Floresta D'Oeste (RO)         NaN
4        Sorghum  1976  Alta Floresta D'Oeste (RO)         NaN
...          ...   ...                         ...         ...
2558975      Pea  2017               Brasília (DF)         7.0
2558976   Barley  2018               Brasília (DF)         4.5
2558977      Pea  2018               Brasília (DF)         7.0
2558978   Barley  2019               Brasília (DF)         4.5
2558979      Pea  2019               Brasília (DF)         7.0

[2558980 rows x 4 columns]

In [11]:
pivot

Year                             1974  1975      1976  1977      1978  1979  \
State                Grain
Abadia de Goiás (GO) Barley       0.0   0.0  0.000000   0.0  0.000000   0.0
                     Beans        0.0   0.0  0.000000   0.0  0.000000   0.0
                     Fava Beans   0.0   0.0  0.000000   0.0  0.000000   0.0
                     Maize        0.0   0.0  0.000000   0.0  0.000000   0.0
                     Oats         0.0   0.0  0.000000   0.0  0.000000   0.0
...                               ...   ...       ...   ...       ...   ...
Óleo (SP)            Pea          0.0   0.0  0.000000   0.0  0.000000   0.0
                     Rye          0.0   0.0  0.000000   0.0  0.000000   0.0
                     Sorghum      0.0   0.0  0.000000   0.0  0.000000   0.0
                     Soybeans     1.2   1.0  1.004082   1.2  0.750586   1.5
                     Wheat        1.0   1.0  0.988858   0.6  0.536585   0.0

Year                             1980  1981  1982  1983  ...      2010  \
State                Grain                               ...
Abadia de Goiás (GO) Barley       0.0   0.0   0.0   0.0  ...  0.000000
                     Beans        0.0   0.0   0.0   0.0  ...  0.000000
                     Fava Beans   0.0   0.0   0.0   0.0  ...  0.000000
                     Maize        0.0   0.0   0.0   0.0  ...  4.500000
                     Oats         0.0   0.0   0.0   0.0  ...  0.000000
...                               ...   ...   ...   ...  ...       ...
Óleo (SP)            Pea          0.0   0.0   0.0   0.0  ...  0.000000
                     Rye          0.0   0.0   0.0   0.0  ...  0.000000
                     Sorghum      0.0   0.0   0.0   0.0  ...  0.000000
                     Soybeans     2.1   0.0   1.8   0.0  ...  3.302013
                     Wheat        0.0   0.0   0.0   0.0  ...  2.750000

Year                                 2011  2012      2013      2014  2015  \
State                Grain
Abadia de Goiás (GO) Barley      0.000000   0.0  0.000000  0.000000   0.0
                     Beans       0.000000   0.0  0.000000  0.000000   0.0
                     Fava Beans  0.000000   0.0  0.000000  0.000000   0.0
                     Maize       5.000000   5.0  6.000000  6.500000   6.5
                     Oats        0.000000   0.0  0.000000  0.000000   0.0
...                                   ...   ...       ...       ...   ...
Óleo (SP)            Pea         0.000000   0.0  0.000000  0.000000   0.0
                     Rye         0.000000   0.0  0.000000  0.000000   0.0
                     Sorghum     0.000000   0.0  0.000000  0.000000   0.0
                     Soybeans    3.302013   3.4  2.984211  2.992308   2.7
                     Wheat       2.750000   0.0  0.000000  0.000000   0.0

Year                                 2016      2017      2018      2019
State                Grain
Abadia de Goiás (GO) Barley      0.000000  0.000000  0.000000  0.000000
                     Beans       0.000000  0.000000  0.000000  0.000000
                     Fava Beans  0.000000  0.000000  0.000000  0.000000
                     Maize       3.800000  0.000000  0.000000  6.900000
                     Oats        0.000000  0.000000  0.000000  0.000000
...                                   ...       ...       ...       ...
Óleo (SP)            Pea         0.000000  0.000000  0.000000  0.000000
                     Rye         0.000000  0.000000  0.000000  0.000000
                     Sorghum     0.000000  0.000000  0.000000  4.000000
                     Soybeans    2.673973  2.673973  2.947945  3.001412
                     Wheat       0.000000  0.000000  0.000000  0.000000

[55630 rows x 46 columns]

In [12]:
agro.set_index(['Grain','Year']) # fiz um indice multinivel

,,Alta Floresta D'Oeste (RO),Ariquemes (RO),Cabixi (RO),Cacoal (RO),Cerejeiras (RO),Colorado do Oeste (RO),Corumbiara (RO),Costa Marques (RO),Espigão D'Oeste (RO),Guajará-Mirim (RO),...,Uruaçu (GO),Uruana (GO),Urutaí (GO),Valparaíso de Goiás (GO),Varjão (GO),Vianópolis (GO),Vicentinópolis (GO),Vila Boa (GO),Vila Propício (GO),Brasília (DF)
Grain,Year,,,,,,,,,,,,,,,,,,,,,
Sorghum,1974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Wheat,1974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sorghum,1975,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Wheat,1975,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sorghum,1976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Pea,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0
Barley,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.5
Pea,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0
Barley,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.5
Pea,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0

In [15]:
agro.reset_index(inplace=True) # fiz um indice multinivel

In [16]:
agro.drop(["index"], axis=1, inplace=True) # apliquei dnv porque voltou quando usei o reset

In [17]:
agro

,Grain,Year,Alta Floresta D'Oeste (RO),Ariquemes (RO),Cabixi (RO),Cacoal (RO),Cerejeiras (RO),Colorado do Oeste (RO),Corumbiara (RO),Costa Marques (RO),...,Uruaçu (GO),Uruana (GO),Urutaí (GO),Valparaíso de Goiás (GO),Varjão (GO),Vianópolis (GO),Vicentinópolis (GO),Vila Boa (GO),Vila Propício (GO),Brasília (DF)
0,Sorghum,1974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Wheat,1974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sorghum,1975,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Wheat,1975,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Sorghum,1976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
455,Pea,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0
456,Barley,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.5
457,Pea,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0
458,Barley,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.5
459,Pea,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0

In [18]:
producao = agro["Ariquemes (RO)"].to_numpy() # tranformando a coluna Ariquemes em um array numpy

In [19]:
producao

array([       nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
       1.4600639 ,        nan, 1.37145183,        nan, 1.79928571,
              nan, 1.8       ,        nan, 1.8       ,        nan,
       1.4       ,        nan, 1.54937076,        nan, 1.82222852,
              nan, 1.60791199,        nan, 1.59851477,        nan,
       1.5999662 ,        nan, 1.6       ,        nan, 1.6       ,
              nan, 1.6       ,        nan, 1.6       ,        nan,
       1.60012063,        nan, 1.06984925,        nan, 1.06984925,
              nan, 1.20013432,        nan, 1.20012849,        nan,
       0.86503759,        nan, 0.865     ,        nan, 1.2       ,
              nan, 1.2       ,        nan, 1.426     , 2.4       ,
       1.5       ,        nan, 1.6       ,        nan, 1.8       ,
              nan, 1.90012804, 2.8       , 1.94994179,        nan,
       1.94994179,        nan, 2.        , 3.        , 2.        ,
       3.        , 1.5       , 2.7       , 1.2       , 3.        ,
       1.2       , 3.        , 3.52767053, 3.        , 3.51942446,
       3.30004458, 3.51506456, 3.29980751, 3.41538462, 3.29990967,
       3.6       , 3.        , 3.6       , 3.11567211,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan, 0.5601318 ,        nan,
       0.55990676,        nan, 0.33511111,        nan, 0.27991734,
              nan, 0.467     ,        nan, 0.48      ,        nan,
       0.62063492,        nan, 0.4199536 ,        nan, 0.46636938,
              nan, 0.48014094,        nan, 0.5       ,        nan,
       0.3       ,        nan, 0.5       ,        nan, 0.6       ,
              nan, 0.6       ,        nan, 0.21270452,        nan,
       0.21259843,        nan, 0.4       ,        nan, 0.5993266 ,
              nan, 0.60064412,        nan, 0.59956236,        nan,
       0.47931034,        nan, 0.4       ,        nan, 0.41923077,
              nan, 0.44808743,        nan, 0.39903846,        nan,
       0.41928721,        nan, 0.25090909,        nan, 0.4       ,
              nan, 0.41975309,        nan, 0.45030251,        nan,
       0.45034965,        nan, 0.13496503,        nan, 0.17972028,
              nan, 0.17942584,        nan, 0.4       ,        nan,
       0.35      ,        nan, 0.36666667,        nan, 0.3       ,
              nan, 0.36      ,        nan, 0.4       ,        nan,
       0.4       ,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan])

In [20]:
print(type(producao))

<class 'numpy.ndarray'>

In [21]:
producao_mais_10 = producao + 10 # somei mais em todos na produção

In [22]:
producao_mais_10

array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
       11.4600639 ,         nan, 11.37145183,         nan, 11.79928571,
               nan, 11.8       ,         nan, 11.8       ,         nan,
       11.4       ,         nan, 11.54937076,         nan, 11.82222852,
               nan, 11.60791199,         nan, 11.59851477,         nan,
       11.5999662 ,         nan, 11.6       ,         nan, 11.6       ,
               nan, 11.6       ,         nan, 11.6       ,         nan,
       11.60012063,         nan, 11.06984925,         nan, 11.06984925,
               nan, 11.20013432,         nan, 11.20012849,         nan,
       10.86503759,         nan, 10.865     ,         nan, 11.2       ,
               nan, 11.2       ,         nan, 11.426     , 12.4       ,
       11.5       ,         nan, 11.6       ,         nan, 11.8       ,
               nan, 11.90012804, 12.8       , 11.94994179,         nan,
       11.94994179,         nan, 12.        , 13.        , 12.        ,
       13.        , 11.5       , 12.7       , 11.2       , 13.        ,
       11.2       , 13.        , 13.52767053, 13.        , 13.51942446,
       13.30004458, 13.51506456, 13.29980751, 13.41538462, 13.29990967,
       13.6       , 13.        , 13.6       , 13.11567211,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan, 10.5601318 ,         nan,
       10.55990676,         nan, 10.33511111,         nan, 10.27991734,
               nan, 10.467     ,         nan, 10.48      ,         nan,
       10.62063492,         nan, 10.4199536 ,         nan, 10.46636938,
               nan, 10.48014094,         nan, 10.5       ,         nan,
       10.3       ,         nan, 10.5       ,         nan, 10.6       ,
               nan, 10.6       ,         nan, 10.21270452,         nan,
       10.21259843,         nan, 10.4       ,         nan, 10.5993266 ,
               nan, 10.60064412,         nan, 10.59956236,         nan,
       10.47931034,         nan, 10.4       ,         nan, 10.41923077,
               nan, 10.44808743,         nan, 10.39903846,         nan,
       10.41928721,         nan, 10.25090909,         nan, 10.4       ,
               nan, 10.41975309,         nan, 10.45030251,         nan,
       10.45034965,         nan, 10.13496503,         nan, 10.17972028,
               nan, 10.17942584,         nan, 10.4       ,         nan,
       10.35      ,         nan, 10.36666667,         nan, 10.3       ,
               nan, 10.36      ,         nan, 10.4       ,         nan,
       10.4       ,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan])

In [25]:
print(producao[0:5]) # pegando os 5 primeiros

[nan nan nan nan nan]

In [26]:
agro_long["Grain"].value_counts() # contando a qtd de cada cultura

Grain
Sorghum       255898
Wheat         255898
Maize         255898
Soybeans      255898
Fava Beans    255898
Beans         255898
Oats          255898
Rye           255898
Barley        255898
Pea           255898
Name: count, dtype: int64

In [30]:
agro_long["State"].value_counts() # a quantidade de registros de cada municipoio fica igual pois tudo é completado por nan caso não tenha

State
Alta Floresta D'Oeste (RO)    460
Ariquemes (RO)                460
Cabixi (RO)                   460
Cacoal (RO)                   460
Cerejeiras (RO)               460
                             ...
Vianópolis (GO)               460
Vicentinópolis (GO)           460
Vila Boa (GO)                 460
Vila Propício (GO)            460
Brasília (DF)                 460
Name: count, Length: 5563, dtype: int64

In [32]:
def categorizar_producao(valor):
    if pd.isna(valor):
        return "Sem dado"
    elif valor < 100:
        return "Baixa produção"
    elif valor < 1000:
        return "Média produção"
    else:
        return "Alta produção"

In [33]:
agro_long["Categoria_Producao"] = agro_long["Production"].apply(categorizar_producao) # classificando as produções

In [36]:
agro_long[agro_long["Production"].notna()].head(10) # visualizando

     Grain  Year                       State  Production Categoria_Producao
118  Maize  1987  Alta Floresta D'Oeste (RO)    1.600000     Baixa produção
120  Maize  1988  Alta Floresta D'Oeste (RO)    1.600000     Baixa produção
122  Maize  1989  Alta Floresta D'Oeste (RO)    1.600000     Baixa produção
124  Maize  1990  Alta Floresta D'Oeste (RO)    1.600000     Baixa produção
126  Maize  1991  Alta Floresta D'Oeste (RO)    1.600000     Baixa produção
128  Maize  1992  Alta Floresta D'Oeste (RO)    1.600000     Baixa produção
130  Maize  1993  Alta Floresta D'Oeste (RO)    1.600000     Baixa produção
132  Maize  1994  Alta Floresta D'Oeste (RO)    1.742929     Baixa produção
134  Maize  1995  Alta Floresta D'Oeste (RO)    1.742973     Baixa produção
136  Maize  1996  Alta Floresta D'Oeste (RO)    1.300046     Baixa produção

In [37]:
agro.to_csv("Final")