In [2]:
import pandas as pd

In [4]:
data = {'Empresa':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Nome':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Venda':[200,120,340,124,243,350]}

In [5]:
df = pd.DataFrame(data)

In [6]:
df

  Empresa     Nome  Venda
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [7]:
df.groupby('Empresa') # faz o agupamento é basicamente falar quem vc quer agrupar

In [15]:
group = df.groupby("Empresa")

In [17]:
group.sum(numeric_only=True)# essa versão do curso não esta mais funcionando por_companhia.mean()

         Venda
Empresa
FB         593
GOOG       320
MSFT       464

In [21]:
group.describe()

        Venda
        count   mean         std    min     25%    50%     75%    max
Empresa
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [26]:
group = df.groupby("Nome") # pode usdar qualque label

In [27]:
group

In [28]:
group.count()

         Empresa  Venda
Nome
Amy            1      1
Carl           1      1
Charlie        1      1
Sam            1      1
Sarah          1      1
Vanessa        1      1